ALTER TABLE PMSCODES
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_PMSCODES;

/* 코드성데이터 테이블 */
DROP TABLE PMSCODES 
	CASCADE CONSTRAINTS;

/* 코드성데이터 테이블 */
CREATE TABLE PMSCODES (
	cno NUMBER NOT NULL, /* 코드번호 */
	refno NUMBER NOT NULL, /* 부모코드번호 */
	cname VARCHAR2(30) NOT NULL /* 이름 */
);

COMMENT ON TABLE PMSCODES IS '코드성데이터 테이블';

COMMENT ON COLUMN PMSCODES.cno IS '코드번호';

COMMENT ON COLUMN PMSCODES.refno IS '부모코드번호';

COMMENT ON COLUMN PMSCODES.cname IS '이름';

CREATE UNIQUE INDEX PK_PMSCODES
	ON PMSCODES (
		cno ASC
	);

ALTER TABLE PMSCODES
	ADD
		CONSTRAINT PK_PMSCODES
		PRIMARY KEY (
			cno
		);
	
ALTER TABLE PMSEMP
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_PMSEMP;

/* 사원정보 */
DROP TABLE PMSEMP 
	CASCADE CONSTRAINTS;

/* 사원정보 */
CREATE TABLE PMSEMP (
	eno NUMBER NOT NULL, /* 사원번호 */
	name VARCHAR2(30) NOT NULL, /* 이름 */
	dept VARCHAR2(50), /* 부서명 */
	grade VARCHAR2(50) NOT NULL, /* 직책 */
	phone VARCHAR2(50) NOT NULL, /* 핸드폰 */
	email VARCHAR2(50) NOT NULL /* 이메일 */
);

COMMENT ON TABLE PMSEMP IS '사원정보';

COMMENT ON COLUMN PMSEMP.eno IS '사원번호';

COMMENT ON COLUMN PMSEMP.name IS '이름';

COMMENT ON COLUMN PMSEMP.dept IS '부서명';

COMMENT ON COLUMN PMSEMP.grade IS '직책';

COMMENT ON COLUMN PMSEMP.phone IS '핸드폰';

COMMENT ON COLUMN PMSEMP.email IS '이메일';

CREATE UNIQUE INDEX PK_PMSEMP
	ON PMSEMP (
		eno ASC
	);

ALTER TABLE PMSEMP
	ADD
		CONSTRAINT PK_PMSEMP
		PRIMARY KEY (
			eno
		);
		
ALTER TABLE PMSMEMBER
	DROP
		CONSTRAINT FK_PMSPROJECT_TO_PMSMEMBER
		CASCADE;

ALTER TABLE PMSMEMBER
	DROP
		CONSTRAINT FK_PMSEMP_TO_PMSMEMBER
		CASCADE;

ALTER TABLE PMSMEMBER
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_PMSMEMBER;

/* 사용자 */
DROP TABLE PMSMEMBER 
	CASCADE CONSTRAINTS;

/* 사용자 */
CREATE TABLE PMSMEMBER (
	mno NUMBER NOT NULL, /* 사원번호 */
	pass VARCHAR2(20) NOT NULL, /* 비밀번호 */
	mdiv NUMBER NOT NULL, /* 권한구분 */
	wcon VARCHAR2(50), /* 희망연락처 */
	pno NUMBER /* 프로젝트번호 */
);

COMMENT ON TABLE PMSMEMBER IS '사용자';

COMMENT ON COLUMN PMSMEMBER.mno IS '사원번호';

COMMENT ON COLUMN PMSMEMBER.pass IS '비밀번호';

COMMENT ON COLUMN PMSMEMBER.mdiv IS '권한구분';

COMMENT ON COLUMN PMSMEMBER.wcon IS '희망연락처';

COMMENT ON COLUMN PMSMEMBER.pno IS '프로젝트번호';

CREATE UNIQUE INDEX PK_PMSMEMBER
	ON PMSMEMBER (
		mno ASC
	);

ALTER TABLE PMSMEMBER
	ADD
		CONSTRAINT PK_PMSMEMBER
		PRIMARY KEY (
			mno
		);

ALTER TABLE PMSMEMBER
	ADD
		CONSTRAINT FK_PMSEMP_TO_PMSMEMBER
		FOREIGN KEY (
			mno
		)
		REFERENCES PMSEMP (
			eno
		);
	
ALTER TABLE pmsmember
	ADD
		CONSTRAINT pmsmember_mdiv_ck
		CHECK(mdiv IN(2,3,4,5,6));
	
ALTER TABLE PMSPROJECT
	DROP
		CONSTRAINT FK_PMSMEMBER_TO_PMSPROJECT
		CASCADE;

ALTER TABLE PMSPROJECT
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_PMSPROJECT;

/* 프로젝트 */
DROP TABLE PMSPROJECT 
	CASCADE CONSTRAINTS;

/* 프로젝트 */
CREATE TABLE PMSPROJECT (
	pno NUMBER NOT NULL, /* 프로젝트번호 */
	sdate DATE NOT NULL, /* 시작일자 */
	deadline DATE NOT NULL, /* 종료일자 */
	pname VARCHAR2(100) NOT NULL, /* 프로젝트명 */
	detail VARCHAR2(500) NOT NULL, /* 프로젝트내용 */
	cdate DATE, /* 결재일자 */
	pdiv NUMBER NOT NULL, /* 결재구분 */
	mno NUMBER NOT NULL /* PM번호 */
);

COMMENT ON TABLE PMSPROJECT IS '프로젝트';

COMMENT ON COLUMN PMSPROJECT.pno IS '프로젝트번호';

COMMENT ON COLUMN PMSPROJECT.sdate IS '시작일자';

COMMENT ON COLUMN PMSPROJECT.deadline IS '종료일자';

COMMENT ON COLUMN PMSPROJECT.pname IS '프로젝트명';

COMMENT ON COLUMN PMSPROJECT.detail IS '프로젝트내용';

COMMENT ON COLUMN PMSPROJECT.cdate IS '결재일자';

COMMENT ON COLUMN PMSPROJECT.pdiv IS '결재구분';

COMMENT ON COLUMN PMSPROJECT.mno IS 'PM번호';

CREATE UNIQUE INDEX PK_PMSPROJECT
	ON PMSPROJECT (
		pno ASC
	);

ALTER TABLE PMSPROJECT
	ADD
		CONSTRAINT PK_PMSPROJECT
		PRIMARY KEY (
			pno
		);

ALTER TABLE PMSPROJECT
	ADD
		CONSTRAINT FK_PMSMEMBER_TO_PMSPROJECT
		FOREIGN KEY (
			mno
		)
		REFERENCES PMSMEMBER (
			mno
		);
	
ALTER TABLE pmsproject
	ADD
		CONSTRAINT pmsproject_pdiv_ck
		CHECK(pdiv IN(11,12,13,14));
	
ALTER TABLE PMSMEMBER
	ADD
		CONSTRAINT FK_PMSPROJECT_TO_PMSMEMBER
		FOREIGN KEY (
			pno
		)
		REFERENCES PMSPROJECT (
			pno
		);
	
ALTER TABLE PMSLOG
	DROP
		CONSTRAINT FK_PMSMEMBER_TO_PMSLOG
		CASCADE;

ALTER TABLE PMSLOG
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_PMSLOG;

/* 로그인히스토리 */
DROP TABLE PMSLOG 
	CASCADE CONSTRAINTS;

/* 로그인히스토리 */
CREATE TABLE PMSLOG (
	lno NUMBER NOT NULL, /* 순번 */
	state NUMBER NOT NULL, /* 로그인상태 */
	login DATE NOT NULL, /* 로그인일시 */
	logout DATE, /* 로그아웃일시 */
	mno NUMBER NOT NULL /* 사원번호 */
);

COMMENT ON TABLE PMSLOG IS '로그인히스토리';

COMMENT ON COLUMN PMSLOG.lno IS '순번';

COMMENT ON COLUMN PMSLOG.state IS '로그인상태';

COMMENT ON COLUMN PMSLOG.login IS '로그인일시';

COMMENT ON COLUMN PMSLOG.logout IS '로그아웃일시';

COMMENT ON COLUMN PMSLOG.mno IS '사원번호';

CREATE UNIQUE INDEX PK_PMSLOG
	ON PMSLOG (
		lno ASC
	);

ALTER TABLE PMSLOG
	ADD
		CONSTRAINT PK_PMSLOG
		PRIMARY KEY (
			lno
		);

ALTER TABLE PMSLOG
	ADD
		CONSTRAINT FK_PMSMEMBER_TO_PMSLOG
		FOREIGN KEY (
			mno
		)
		REFERENCES PMSMEMBER (
			mno
		);
	
ALTER TABLE pmslog
	ADD
		CONSTRAINT pmslog_state_ck
		CHECK(state IN(0,1));
	
ALTER TABLE PMSTASK
	DROP
		CONSTRAINT FK_PMSPROJECT_TO_PMSTASK
		CASCADE;

ALTER TABLE PMSTASK
	DROP
		CONSTRAINT FK_PMSMEMBER_TO_PMSTASK
		CASCADE;

ALTER TABLE PMSTASK
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_PMSTASK;

/* 프로젝트업무 */
DROP TABLE PMSTASK 
	CASCADE CONSTRAINTS;

/* 프로젝트업무 */
CREATE TABLE PMSTASK (
	tno NUMBER NOT NULL, /* 업무번호 */
	pno NUMBER NOT NULL, /* 프로젝트번호 */
	refno NUMBER NOT NULL, /* 부모업무번호 */
	tname VARCHAR2(100) NOT NULL, /* 업무명 */
	sdate DATE NOT NULL, /* 시작일자 */
	edate DATE NOT NULL, /* 종료일자 */
	prog NUMBER NOT NULL, /* 진행율 */
	pdate DATE, /* 진행일자 */
	coment VARCHAR2(200), /* 반려사유 */
	tdiv NUMBER NOT NULL, /* 결재구분 */
	mno NUMBER NOT NULL /* 사원번호 */
);

COMMENT ON TABLE PMSTASK IS '프로젝트업무';

COMMENT ON COLUMN PMSTASK.tno IS '업무번호';

COMMENT ON COLUMN PMSTASK.pno IS '프로젝트번호';

COMMENT ON COLUMN PMSTASK.refno IS '부모업무번호';

COMMENT ON COLUMN PMSTASK.tname IS '업무명';

COMMENT ON COLUMN PMSTASK.sdate IS '시작일자';

COMMENT ON COLUMN PMSTASK.edate IS '종료일자';

COMMENT ON COLUMN PMSTASK.prog IS '진행율';

COMMENT ON COLUMN PMSTASK.pdate IS '진행일자';

COMMENT ON COLUMN PMSTASK.coment IS '반려사유';

COMMENT ON COLUMN PMSTASK.tdiv IS '결재구분';

COMMENT ON COLUMN PMSTASK.mno IS '사원번호';

CREATE UNIQUE INDEX PK_PMSTASK
	ON PMSTASK (
		tno ASC
	);

ALTER TABLE PMSTASK
	ADD
		CONSTRAINT PK_PMSTASK
		PRIMARY KEY (
			tno
		);

ALTER TABLE PMSTASK
	ADD
		CONSTRAINT FK_PMSPROJECT_TO_PMSTASK
		FOREIGN KEY (
			pno
		)
		REFERENCES PMSPROJECT (
			pno
		);

ALTER TABLE PMSTASK
	ADD
		CONSTRAINT FK_PMSMEMBER_TO_PMSTASK
		FOREIGN KEY (
			mno
		)
		REFERENCES PMSMEMBER (
			mno
		);	
	
ALTER TABLE pmstask
	ADD
		CONSTRAINT pmstask_tdiv_ck
		CHECK(tdiv IN(21,22,23,24));
	
ALTER TABLE PMSTFILE
	DROP
		CONSTRAINT FK_PMSTASK_TO_PMSTFILE
		CASCADE;

ALTER TABLE PMSTFILE
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_PMSTFILE;

/* 업무첨부파일 */
DROP TABLE PMSTFILE 
	CASCADE CONSTRAINTS;

/* 업무첨부파일 */
CREATE TABLE PMSTFILE (
	tfno NUMBER NOT NULL, /* 파일번호 */
	tno NUMBER NOT NULL, /* 업무번호 */
	fname VARCHAR2(200) NOT NULL, /* 파일명 */
	upload DATE NOT NULL /* 업로드일 */
);

COMMENT ON TABLE PMSTFILE IS '업무첨부파일';

COMMENT ON COLUMN PMSTFILE.tfno IS '파일번호';

COMMENT ON COLUMN PMSTFILE.tno IS '업무번호';

COMMENT ON COLUMN PMSTFILE.fname IS '파일명';

COMMENT ON COLUMN PMSTFILE.upload IS '업로드일';

CREATE UNIQUE INDEX PK_PMSTFILE
	ON PMSTFILE (
		tfno ASC
	);

ALTER TABLE PMSTFILE
	ADD
		CONSTRAINT PK_PMSTFILE
		PRIMARY KEY (
			tfno
		);

ALTER TABLE PMSTFILE
	ADD
		CONSTRAINT FK_PMSTASK_TO_PMSTFILE
		FOREIGN KEY (
			tno
		)
		REFERENCES PMSTASK (
			tno
		);
	
ALTER TABLE PMSNOTICE
	DROP
		CONSTRAINT FK_PMSPROJECT_TO_PMSNOTICE
		CASCADE;

ALTER TABLE PMSNOTICE
	DROP
		CONSTRAINT FK_PMSMEMBER_TO_PMSNOTICE
		CASCADE;

ALTER TABLE PMSNOTICE
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_PMSNOTICE;

/* 공지사항 */
DROP TABLE PMSNOTICE 
	CASCADE CONSTRAINTS;

/* 공지사항 */
CREATE TABLE PMSNOTICE (
	nno NUMBER NOT NULL, /* 공지번호 */
	title VARCHAR2(100) NOT NULL, /* 제목 */
	detail VARCHAR2(2000) NOT NULL, /* 내용 */
	wdate DATE NOT NULL, /* 작성일 */
	chdate DATE, /* 수정일 */
	views NUMBER NOT NULL, /* 조회수 */
	pno NUMBER NOT NULL, /* 프로젝트번호 */
	mno NUMBER NOT NULL /* 작성자번호 */
);

COMMENT ON TABLE PMSNOTICE IS '공지사항';

COMMENT ON COLUMN PMSNOTICE.nno IS '공지번호';

COMMENT ON COLUMN PMSNOTICE.title IS '제목';

COMMENT ON COLUMN PMSNOTICE.detail IS '내용';

COMMENT ON COLUMN PMSNOTICE.wdate IS '작성일';

COMMENT ON COLUMN PMSNOTICE.chdate IS '수정일';

COMMENT ON COLUMN PMSNOTICE.views IS '조회수';

COMMENT ON COLUMN PMSNOTICE.pno IS '프로젝트번호';

COMMENT ON COLUMN PMSNOTICE.mno IS '작성자번호';

CREATE UNIQUE INDEX PK_PMSNOTICE
	ON PMSNOTICE (
		nno ASC
	);

ALTER TABLE PMSNOTICE
	ADD
		CONSTRAINT PK_PMSNOTICE
		PRIMARY KEY (
			nno
		);

ALTER TABLE PMSNOTICE
	ADD
		CONSTRAINT FK_PMSPROJECT_TO_PMSNOTICE
		FOREIGN KEY (
			pno
		)
		REFERENCES PMSPROJECT (
			pno
		);

ALTER TABLE PMSNOTICE
	ADD
		CONSTRAINT FK_PMSMEMBER_TO_PMSNOTICE
		FOREIGN KEY (
			mno
		)
		REFERENCES PMSMEMBER (
			mno
		);
	
ALTER TABLE PMSMEETING
	DROP
		CONSTRAINT FK_PMSMEMBER_TO_PMSMEETING
		CASCADE;

ALTER TABLE PMSMEETING
	DROP
		CONSTRAINT FK_PMSPROJECT_TO_PMSMEETING
		CASCADE;

ALTER TABLE PMSMEETING
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_PMSMEETING;

/* 회의록 게시판 */
DROP TABLE PMSMEETING 
	CASCADE CONSTRAINTS;

/* 회의록 게시판 */
CREATE TABLE PMSMEETING (
	mnno NUMBER NOT NULL, /* 회의록번호 */
	topic VARCHAR2(100) NOT NULL, /* 안건 */
	detail VARCHAR2(2000) NOT NULL, /* 내용 */
	result VARCHAR2(200), /* 결정사항 */
	etc VARCHAR2(200), /* 특이사항 */
	views NUMBER NOT NULL, /* 조회수 */
	wdate DATE NOT NULL, /* 작성일 */
	chdate DATE, /* 수정일 */
	mdate DATE NOT NULL, /* 회의일시 */
	loc VARCHAR2(100) NOT NULL, /* 회의장소 */
	people VARCHAR2(200) NOT NULL, /* 참여자 */
	mndiv NUMBER NOT NULL, /* 결재구분 */
	mno NUMBER NOT NULL, /* 작성자번호 */
	pno NUMBER NOT NULL /* 프로젝트번호 */
);

COMMENT ON TABLE PMSMEETING IS '회의록 게시판';

COMMENT ON COLUMN PMSMEETING.mnno IS '회의록번호';

COMMENT ON COLUMN PMSMEETING.topic IS '안건';

COMMENT ON COLUMN PMSMEETING.detail IS '내용';

COMMENT ON COLUMN PMSMEETING.result IS '결정사항';

COMMENT ON COLUMN PMSMEETING.etc IS '특이사항';

COMMENT ON COLUMN PMSMEETING.views IS '조회수';

COMMENT ON COLUMN PMSMEETING.wdate IS '작성일';

COMMENT ON COLUMN PMSMEETING.chdate IS '수정일';

COMMENT ON COLUMN PMSMEETING.mdate IS '회의일시';

COMMENT ON COLUMN PMSMEETING.loc IS '회의장소';

COMMENT ON COLUMN PMSMEETING.people IS '참여자';

COMMENT ON COLUMN PMSMEETING.mndiv IS '결재구분';

COMMENT ON COLUMN PMSMEETING.mno IS '작성자번호';

COMMENT ON COLUMN PMSMEETING.pno IS '프로젝트번호';

CREATE UNIQUE INDEX PK_PMSMEETING
	ON PMSMEETING (
		mnno ASC
	);

ALTER TABLE PMSMEETING
	ADD
		CONSTRAINT PK_PMSMEETING
		PRIMARY KEY (
			mnno
		);

ALTER TABLE PMSMEETING
	ADD
		CONSTRAINT FK_PMSMEMBER_TO_PMSMEETING
		FOREIGN KEY (
			mno
		)
		REFERENCES PMSMEMBER (
			mno
		);

ALTER TABLE PMSMEETING
	ADD
		CONSTRAINT FK_PMSPROJECT_TO_PMSMEETING
		FOREIGN KEY (
			pno
		)
		REFERENCES PMSPROJECT (
			pno
		);
	
ALTER TABLE pmsmeeting
	ADD
		CONSTRAINT pmmeeting_mndiv_ck
		CHECK(mndiv IN(31,32,33,34));
	
ALTER TABLE PMSISSUE
	DROP
		CONSTRAINT FK_PMSPROJECT_TO_PMSISSUE
		CASCADE;

ALTER TABLE PMSISSUE
	DROP
		CONSTRAINT FK_PMSMEMBER_TO_PMSISSUE
		CASCADE;

ALTER TABLE PMSISSUE
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_PMSISSUE;

/* 이슈리스트 */
DROP TABLE PMSISSUE 
	CASCADE CONSTRAINTS;

/* 이슈리스트 */
CREATE TABLE PMSISSUE (
	ino NUMBER NOT NULL, /* 이슈번호 */
	title VARCHAR2(200) NOT NULL, /* 제목 */
	detail VARCHAR2(2000) NOT NULL, /* 내용 */
	views NUMBER NOT NULL, /* 조회수 */
	coment VARCHAR2(2000), /* 해결방안 */
	wdate DATE NOT NULL, /* 작성일 */
	chdate DATE, /* 수정일 */
	cdate DATE, /* 해결방안작성일 */
	pno NUMBER NOT NULL, /* 프로젝트번호 */
	mno NUMBER NOT NULL /* 사원번호 */
);

COMMENT ON TABLE PMSISSUE IS '이슈리스트';

COMMENT ON COLUMN PMSISSUE.ino IS '이슈번호';

COMMENT ON COLUMN PMSISSUE.title IS '제목';

COMMENT ON COLUMN PMSISSUE.detail IS '내용';

COMMENT ON COLUMN PMSISSUE.views IS '조회수';

COMMENT ON COLUMN PMSISSUE.coment IS '해결방안';

COMMENT ON COLUMN PMSISSUE.wdate IS '작성일';

COMMENT ON COLUMN PMSISSUE.chdate IS '수정일';

COMMENT ON COLUMN PMSISSUE.cdate IS '해결방안작성일';

COMMENT ON COLUMN PMSISSUE.pno IS '프로젝트번호';

COMMENT ON COLUMN PMSISSUE.mno IS '사원번호';

CREATE UNIQUE INDEX PK_PMSISSUE
	ON PMSISSUE (
		ino ASC
	);

ALTER TABLE PMSISSUE
	ADD
		CONSTRAINT PK_PMSISSUE
		PRIMARY KEY (
			ino
		);

ALTER TABLE PMSISSUE
	ADD
		CONSTRAINT FK_PMSPROJECT_TO_PMSISSUE
		FOREIGN KEY (
			pno
		)
		REFERENCES PMSPROJECT (
			pno
		);

ALTER TABLE PMSISSUE
	ADD
		CONSTRAINT FK_PMSMEMBER_TO_PMSISSUE
		FOREIGN KEY (
			mno
		)
		REFERENCES PMSMEMBER (
			mno
		);
	
ALTER TABLE PMSREPLY
	DROP
		CONSTRAINT FK_PMSMEMBER_TO_PMSREPLY
		CASCADE;

ALTER TABLE PMSREPLY
	DROP
		CONSTRAINT FK_PMSISSUE_TO_PMSREPLY
		CASCADE;

ALTER TABLE PMSREPLY
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_PMSREPLY;

/* 이슈댓글 */
DROP TABLE PMSREPLY 
	CASCADE CONSTRAINTS;

/* 이슈댓글 */
CREATE TABLE PMSREPLY (
	rno NUMBER NOT NULL, /* 댓글번호 */
	refno NUMBER NOT NULL, /* 원댓번호 */
	detail VARCHAR2(200) NOT NULL, /* 내용 */
	wdate DATE NOT NULL, /* 작성일 */
	mno NUMBER NOT NULL, /* 사원번호 */
	ino NUMBER NOT NULL /* 이슈번호 */
);

COMMENT ON TABLE PMSREPLY IS '이슈댓글';

COMMENT ON COLUMN PMSREPLY.rno IS '댓글번호';

COMMENT ON COLUMN PMSREPLY.refno IS '원댓번호';

COMMENT ON COLUMN PMSREPLY.detail IS '내용';

COMMENT ON COLUMN PMSREPLY.wdate IS '작성일';

COMMENT ON COLUMN PMSREPLY.mno IS '사원번호';

COMMENT ON COLUMN PMSREPLY.ino IS '이슈번호';

CREATE UNIQUE INDEX PK_PMSREPLY
	ON PMSREPLY (
		rno ASC
	);

ALTER TABLE PMSREPLY
	ADD
		CONSTRAINT PK_PMSREPLY
		PRIMARY KEY (
			rno
		);

ALTER TABLE PMSREPLY
	ADD
		CONSTRAINT FK_PMSMEMBER_TO_PMSREPLY
		FOREIGN KEY (
			mno
		)
		REFERENCES PMSMEMBER (
			mno
		);

ALTER TABLE PMSREPLY
	ADD
		CONSTRAINT FK_PMSISSUE_TO_PMSREPLY
		FOREIGN KEY (
			ino
		)
		REFERENCES PMSISSUE (
			ino
		);
	
ALTER TABLE PMSBFILE
	DROP
		CONSTRAINT FK_PMSMEETING_TO_PMSBFILE
		CASCADE;

ALTER TABLE PMSBFILE
	DROP
		CONSTRAINT FK_PMSISSUE_TO_PMSBFILE
		CASCADE;

ALTER TABLE PMSBFILE
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_PMSBFILE;

/* 게시판첨부파일 */
DROP TABLE PMSBFILE 
	CASCADE CONSTRAINTS;

/* 게시판첨부파일 */
CREATE TABLE PMSBFILE (
	bfno NUMBER NOT NULL, /* 파일번호 */
	mnno NUMBER, /* 회의록번호 */
	ino NUMBER, /* 이슈번호 */
	fname VARCHAR2(200) NOT NULL, /* 파일명 */
	upload DATE NOT NULL /* 업로드일 */
);

COMMENT ON TABLE PMSBFILE IS '게시판첨부파일';

COMMENT ON COLUMN PMSBFILE.bfno IS '파일번호';

COMMENT ON COLUMN PMSBFILE.mnno IS '회의록번호';

COMMENT ON COLUMN PMSBFILE.ino IS '이슈번호';

COMMENT ON COLUMN PMSBFILE.fname IS '파일명';

COMMENT ON COLUMN PMSBFILE.upload IS '업로드일';

CREATE UNIQUE INDEX PK_PMSBFILE
	ON PMSBFILE (
		bfno ASC
	);

ALTER TABLE PMSBFILE
	ADD
		CONSTRAINT PK_PMSBFILE
		PRIMARY KEY (
			bfno
		);

ALTER TABLE PMSBFILE
	ADD
		CONSTRAINT FK_PMSMEETING_TO_PMSBFILE
		FOREIGN KEY (
			mnno
		)
		REFERENCES PMSMEETING (
			mnno
		);

ALTER TABLE PMSBFILE
	ADD
		CONSTRAINT FK_PMSISSUE_TO_PMSBFILE
		FOREIGN KEY (
			ino
		)
		REFERENCES PMSISSUE (
			ino
		);
	
INSERT INTO pmscodes values(1,0,'사원권한');
INSERT INTO pmscodes values(2,1,'CEO');
INSERT INTO pmscodes values(3,1,'CTO');
INSERT INTO pmscodes values(4,1,'PM');
INSERT INTO pmscodes values(5,1,'팀원');
INSERT INTO pmscodes values(6,1,'구분없음');
INSERT INTO pmscodes values(10,0,'프로젝트결재');
INSERT INTO pmscodes values(11,10,'진행중');
INSERT INTO pmscodes values(12,10,'결재신청');
INSERT INTO pmscodes values(13,10,'반려');
INSERT INTO pmscodes values(14,10,'종료');
INSERT INTO pmscodes values(20,0,'업무결재');
INSERT INTO pmscodes values(21,20,'업무수행중');
INSERT INTO pmscodes values(22,20,'결재신청');
INSERT INTO pmscodes values(23,20,'반려');
INSERT INTO pmscodes values(24,20,'결재완료');
INSERT INTO pmscodes values(30,0,'회의록결재');
INSERT INTO pmscodes values(31,30,'작성중');
INSERT INTO pmscodes values(32,30,'결재신청');
INSERT INTO pmscodes values(33,30,'반려');
INSERT INTO pmscodes values(34,30,'결재완료');